# Generated by Django 4.1.7 on 2023-04-25 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(default=None, max_length=200)),
                ('description', models.TextField(default=None)),
                ('company_name', models.CharField(default=None, max_length=200, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('application_status', models.CharField(choices=[('P', 'Pending'), ('O', 'On-Hold'), ('A', 'Approved')], default='P', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employer_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default=None)),
                ('company_name', models.CharField(default=None, max_length=200, null=True)),
                ('location', models.CharField(default=None, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message', models.TextField(default=None, max_length=200)),
                ('applicant', models.CharField(default=None, max_length=200)),
                ('application_status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
