# Generated by Django 4.1.7 on 2023-04-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_employee_notification_employer_notification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer_notification',
            name='applicant',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employer_notification',
            name='application_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
