# Generated by Django 4.1.7 on 2023-04-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_employer_notification_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_notification',
            name='applicant',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee_notification',
            name='message',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='employee_notification',
            name='application_status',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee_notification',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
