# Generated by Django 4.1.7 on 2023-04-28 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_employee_notification_applicant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee_notification',
            old_name='applicant',
            new_name='employer',
        ),
    ]
