# Generated by Django 4.1.7 on 2023-05-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_contact_number_profile_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='email_address',
            new_name='email',
        ),
    ]
