# Generated by Django 4.1.7 on 2023-05-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_first_name_profile_last_name_userlastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='full_name',
        ),
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='employer',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
