# Generated by Django 4.1.7 on 2023-04-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_post_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='application_status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
