# Generated by Django 4.1.7 on 2023-10-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_post_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salary',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
